Settings:
  HungerGamesWorld: world
  ForcefieldSideLength: 300
  FeastFloatingDistance: 3
  MiniFeastFloating: 3
  InvincibilityStartMessage: "&aYou are now invincible!"
  InvincibilityExpireMessage: "&aYou are no longer invincible."
  GameStartMessage: "&6The Hunger Games have begun!"
  NoKitMessage: "&6You haven't selected a kit! Select one before the game starts for items and abilities."

  #<kitname> will be replaced with the name of the player's kit
  KitSelectMessage: "&6You have selected the &l<kitname>&6 kit!"
  
Timer:
  MinimumPlayersToStart: 1
  PlayersToQuickStart: 2
  MinutesToFeast: 1
  
  #These should be specified in seconds
  InitialCountdownTime: 15
  QuickStartCountdownTime: 10
  InvincibilityDuration: 10

KitSettings:
  Assassin:
    #These should be specified in ticks (20t = 1 second)
    AssassinChargeRate: 40
    AssassinDechargeRate: 10
    
    #This is the amount that the assassins dmg is multiplied by when is charge is 100%
    AssassinDamageModifier: 2
 
  Thor:
    #The number of ticks of cooldown in between lightning strikes
    ThorCooldownRate: 40

FeastItems:
  firedoor:
    itemid: 64
    itemdata: 1
    maxquantity: 26
    minquantity: 13
    percentchance: 55
    enchantments:
      - 1|2
  swordofderp:
    itemid: 267
    itemdata: 200
    maxquantity: 1
    minquantity: 1
    percentchance: 25
    itemname: "The Sword of Derp"
    enchantments:
      - 1|2
MiniFeastItems:
  firedoor:
    itemid: 64
    itemdata: 1
    maxquantity: 26
    minquantity: 13
    percentchance: 55
    enchantments:
      - 1|2
  swordofderp:
    itemid: 267
    itemdata: 200
    maxquantity: 1
    minquantity: 1
    percentchance: 25
    itemname: "The Sword of Derp"
    enchantments:
      - 1|2