Settings:
  FreeKits:
     - Archer
     - Hunter
  ForcefieldSideLength: 750
  FireworkDisplayDistance: 15
  FeastFloatingDistance: 3
  MiniFeastFloatingDistance: 3
  #This is a number between 1 and 0. 
  #This is multiplied with the ForcefieldSideLength to get the maximum distance that a feast can be from the spawn.
  FeastBoundaryRatio: .5

  InvincibilityStartMessage: "&aYou are now invincible!"
  InvincibilityExpireMessage: "&aYou are no longer invincible."

  DebugMessages: false
  
  GameStartMessage: "&6The Hunger Games have begun!"
  VictoryMessage: "&6You have won the Hunger Games!"
  #<kitname> will be replaced with the name of the player's kit
  KitSelectMessage: "&6You have selected the &l<kitname>&6 kit!"
  #<playername> will be replaced with the name of the player
  CompassTrackMessage: "&aYou have selected &l<playername>&a!"

  ResetMap: true
  
  KitInformMessage: "&6Choose a kit before the game starts! Choose a kit with '/kit <kitname>', type '/kit list' to see the list of kits you can choose from."
  CannotChangeInProgessMessage: "&6You may not change kits while the game is in progress."
  DoNotHavePermissionMessage: "&6You do not have access to that kit!"
  NoKitMessage: "&6You haven't selected a kit! Select one before the game starts for items and abilities."
  
  TimeLeftToStartMessage: "&6There are only <time> until the game starts!"
  #<time> will be replaced by the current time left to start in minutes and seconds
  PlayersLeftToStartMessage: "&6Only another <players> players are needed to start the game!"
  #<players> will be replaced by the current number of players left to start
  NoKitInfoMessage: "&6No info available for this kit."

  Worldname: HungerGames
KitInfo:
  pyro: "&6This kit sets things on fire."
  hunter: "&6This kit hunts pigs." 
Timer:
  MinimumPlayersToStart: 1
  PlayersToQuickStart: 1
  MinutesToFeast: 2
  
  #These should be specified in seconds
  InitialCountdownTime: 20
  QuickStartCountdownTime: 15
  InvincibilityDuration: 1
  VictoryCelebrationDuration: 20
KitSettings:
  Assassin:
    #These should be specified in ticks (20t = 1 second)
    AssassinChargeRate: 40
    AssassinDechargeRate: 10
    #This is the amount that the assassins dmg is multiplied by when is charge is 100%
    AssassinDamageModifier: 2
  
  Barbarian:
    #This is the inital number of kills to rank up from wood to stone sword
    #Each level of sword costs one more than the previous level (i.e. stone to iron costs 3 if this value is 2)
    KillsToRankUp: 2
    SwordName: "&cTyrfing"
  
  Thor:
    #The number of ticks of cooldown in between lightning strikes
    ThorCooldownRate: 40
  
  Spiderman:
    #The number of ticks of cooldown in between web throws
    SpidermanCooldownRate: 30
    #The number of seconds of time it takes for a spiderman's webs to regenerate
    SpidermanRegenRate: 180
  Flash:
    #Max number of blocks that this kit can teleport to
    FlashMaxRange: 80
    #Specified in seconds
    FlashCooldownRate: 150
    
  Miner:
    #Specified in seconds
    MinerPotionDuration: 10
  
  Pyro:
    PyroFireDuration: 100 #Ticks for which someone ignited by the pyro's fire charges will be on fire.
    PyroFireRadius: 3 #Distance in blocks at which you will be ignited by the pyro's fire charge.

  Snail:
    SnailSlowDurationTicks: 100 #Ticks for which someone hit by a snail will be slowed.
    
  Worm:
    WormBlocksPerFoodUnit: 4
    WormBlocksPerHealth: 5

FeastItems:
  firedoor:
    itemid: 64
    itemdata: 1
    maxquantity: 26
    minquantity: 13
    percentchance: 55
    enchantments:
      - 1|2
  swordofderp:
    itemid: 267
    itemdata: 200
    maxquantity: 1
    minquantity: 1
    percentchance: 25
    itemname: "The Sword of Derp"
    enchantments:
      - 1|2
MiniFeastItems:
  firedoor:
    itemid: 64
    itemdata: 1
    maxquantity: 26
    minquantity: 13
    percentchance: 55
    enchantments:
      - 1|2
 
  swordofderp:
    itemid: 267
    itemdata: 200
    maxquantity: 1
    minquantity: 1
    percentchance: 25
    itemname: "The Sword of Derp"
    enchantments:
      - 1|2