Settings:
  HungerGamesWorld: world
  ForcefieldSideLength: 500
  FeastFloatingDistance: 3
  MiniFeastFloating: 3
  InvincibilityStartMessage: "&aYou are now invincible!"
  InvincibilityExpireMessage: "&aYou are no longer invincible."
  GameStartMessage: "&6The Hunger Games have begun!"
  NoKitMessage: "&6You haven't selected a kit! Select one before the game starts for items and abilities."
  VictoryMessage: "&6You have won the Hunger Games!"
  #<kitname> will be replaced with the name of the player's kit
  KitSelectMessage: "&6You have selected the &l<kitname>&6 kit!"
  #<playername> will be replaced with the name of the player
  CompassTrackMessage: "&aYou have selected &l<playername>&a!"
  ResetMapOnStartup: false
  ResetMapOnGameEnd: true
  
Timer:
  MinimumPlayersToStart: 1
  PlayersToQuickStart: 2
  MinutesToFeast: 1
  
  #These should be specified in seconds
  InitialCountdownTime: 20
  QuickStartCountdownTime: 15
  InvincibilityDuration: 10

KitSettings:
  Assassin:
    #These should be specified in ticks (20t = 1 second)
    AssassinChargeRate: 40
    AssassinDechargeRate: 10
    
    #This is the amount that the assassins dmg is multiplied by when is charge is 100%
    AssassinDamageModifier: 2
  Barbarian:
    #This is the inital number of kills to rank up from wood to stone sword
    #Each level of sword costs one more than the previous level (i.e. stone to iron costs 3 if this value is 2)
    KillsToRankUp: 2
    SwordName: "&cTyrfing"
  Thor:
    #The number of ticks of cooldown in between lightning strikes
    ThorCooldownRate: 40

FeastItems:
  firedoor:
    itemid: 64
    itemdata: 1
    maxquantity: 26
    minquantity: 13
    percentchance: 55
    enchantments:
      - 1|2
  swordofderp:
    itemid: 267
    itemdata: 200
    maxquantity: 1
    minquantity: 1
    percentchance: 25
    itemname: "The Sword of Derp"
    enchantments:
      - 1|2
MiniFeastItems:
  firedoor:
    itemid: 64
    itemdata: 1
    maxquantity: 26
    minquantity: 13
    percentchance: 55
    enchantments:
      - 1|2
  swordofderp:
    itemid: 267
    itemdata: 200
    maxquantity: 1
    minquantity: 1
    percentchance: 25
    itemname: "The Sword of Derp"
    enchantments:
      - 1|2