name: HungerGames
main: me.sleightofmind.hungergames.Main
version: 0.2

commands:
  kit:
    description: Select your kit to play with.
    usage: "NOPE, CHUCK TESTA. Correct usage: /kit select <kitname>"